### ISSUE TITLE
MapAlignerIdentification failed

### ISSUE THREAD

**Issue by david-bouyssie** [userbz/DeMix-Q#3]
I tried to use the DeMix-Q workflow on an in-house dataset. However I'm stuck at node #6 (MapAlignerIdentification) with the following error:
_NOTICE: MapAlignerIdentification of node #6 started. Processing ...
Error: Unexpected internal error (Could not extract retention time information from the reference file)
MapAlignerIdentification failed!_

I looked at the used idxml files and the RT fields has a valid value.
Note that I successfully ran the workflow with the example dataset.
Any advice to fix this issue ?

**Comment by userbz** [comment]
I also found that home-made idXML files are often run into troubles. 
So, I would recommend you to try the new workflow (DeMix_PoseCluster.toppas) for RT alignment, which uses feature maps (featureXML) instead of identifications (idXML) to align individual experiments.

**Comment by david-bouyssie** [comment]
Thank you for your answer.
The suggested alternative workflow works on my datasets.
I had however to create an extra workflow for "mzML -> featureXML" conversion.

**Comment by userbz** [comment]
Hi, Thanks for the comments.
mzML -> featrueXML conversion is basically **feature detection**. You can simply copy the node from the old DeMix-Q workflow or from the DeMix identification workflow to do so. I thought this time-consuming process needs to be done only once, instead of every time.
