### ISSUE TITLE
FeatureFinderCentroided crash

### ISSUE THREAD

**Issue by duernbergerhard** [userbz/DeMix-Q#5]
Hi,

I am using the DeMix.toppas workflow. (DeMix_PoseCluster.toppas did not work for me.)
Unfortunately FeatureFinderCentroided keeps crashing in DeMix.toppas in a certain data set, on other data sets it worked and results look good. 
I found this thread telling I should relax tolerance parameters: https://forum.knime.com/t/error-featurefindercentroided/10377
Which parameters can I try tweaking to get the workflow running?

Many thanks in advance!

Kind regards, Gerhard
[TOPPAS.log](https://github.com/userbz/DeMix-Q/files/2101283/TOPPAS.log)

PS: this is the log message which I get upon crash (full log is attached):
Abort reasons during feature construction:
- Could not extend seed: 22071
- Could not find good enough isotope pattern containing the seed: 42224
- Feature quality too low after fit: 34614
- Invalid feature after fit - too few traces or peaks left: 172652
- Invalid fit: Center outside of feature bounds: 15311
- Invalid fit: Fitted model is bigger than 'max_rt_span': 12644
- Invalid fit: Less than 'min_rt_span' left after fit: 4
FeatureFinderCentroided took 26:56 m (wall), 01:21:46 h (CPU), 47.42 s (system), 01:20:59 h (user).

**Comment by userbz** [comment]
Hi Gerhard,

I checked your log file, I guess the problem might be related to the second mzML file. It seems not having much higher charged species in the file. Would you please try to reduce the maximum charge state to 4 and redo the analysis? 

Best wishes,
Bob

**Comment by duernbergerhard** [comment]
Dear Bob,

thanks for the hint. Unfortunately it crashed again (error msg below)
But in the meantime I could find a workaround by using the _PoseClusters workflow and adding .featureXML files.
Thanks for your fast reply!

Kind regards, Gerhard

-- done [took 01:15 m (CPU), 01:15 m (Wall)] -- 
27199 features left.

Abort reasons during feature construction:
- Could not extend seed: 22087
- Could not find good enough isotope pattern containing the seed: 37332
- Feature quality too low after fit: 28523
- Invalid feature after fit - too few traces or peaks left: 166193
- Invalid fit: Center outside of feature bounds: 3322
- Invalid fit: Fitted model is bigger than 'max_rt_span': 29035
- Invalid fit: Less than 'min_rt_span' left after fit: 13
FeatureFinderCentroided took 22:34 m (wall), 01:10:22 h (CPU), 34.52 s (system), 01:09:47 h (user).

==============================================================================
17:46:05 ERROR: FeatureFinderCentroided crashed!

**Comment by userbz** [comment]
Hi Gerhard,
Indeed, I would recommend using the PoseClusters workflow that separates the feature detection from downstream processes. 
Good luck with your analysis!
/Bob
